version: "3.1"

services:
  service:
    build: .
    ports:
      - "5003:80"
    environment:
      CONNECTIONSTRINGS__GLOBALDATABASE: server=mariadb;user=root;password=example;database=garages-dev

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb-store:/var/lib/mysql
